library(tidyverse)
jpeg("KMeansVisual.jpg",width=960,height=540,res = 150)
dat <- read.table("processed_data.txt")
names(dat) = c("Latitude","Longitude","Cluster")
ggplot(dat)+geom_point(mapping = aes(x=Latitude,y=Longitude,color=factor(Cluster)))
#ggplot(dat)+geom_bar(mapping = aes(x=Cluster,fill=factor(Cluster)),width = 1) + coord_polar()
dev.off()
