library(ggplot2)
library(RColorBrewer)
cols <- colorRampPalette(brewer.pal(8, "Dark2"))
dat <- read.table("processed_data.txt")
names(dat) = c("Latitude","Longitude","Cluster")
maxC <- max(dat[3],na.rm =TRUE)
png("KMeansVisual1.png",units="in",width=9,height=5,res = 300)
ggplot(dat)+geom_point(mapping = aes(x=Latitude,y=Longitude,color=factor(Cluster))) + scale_color_manual(values = cols(maxC))
dev.off()
png("KMeansVisual2.png",units="in",width=9,height=5,res = 300)
ggplot(dat)+geom_bar(mapping = aes(x=Cluster,fill=factor(Cluster)),width = 1) + coord_polar() + scale_fill_manual(values = cols(maxC))
dev.off()
